name: CI Deploy & Notify

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: |
          npm ci
      - name: Build assets
        run: |
          npm run build
      - name: Firebase Deploy
        uses: w9jds/firebase-action@v2
        with:
          args: deploy --only hosting --project expense-tracker-prod-df355
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Notify smoke workflow (repository_dispatch)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOSTING_URL: https://expense-tracker-prod-df355.web.app
          DEPLOY_ID: ${{ github.sha }}
        run: |
          node scripts/notify-github-deploy.js
